[build]
  base = "CAFE-MENU-CARD-GENERATOR-main(1)/CAFE-MENU-CARD-GENERATOR-main/frontend"
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
